# # See https://pre-commit.com for more information
# # See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
        #- --in-place
        - --remove-all-unused-imports

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args:
        - --line-length=170


-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    # -   id: check-docstring-first
    -   id: detect-private-key

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args:
        - --max-line-length=170
        - --max-doc-length=170
        - --ignore=E203,W503,E712,E731, F841, F821, E402
        # E712 comparision funktioniert nicht gut mit inplace operationen von pandas deshalb deaktiviert.
        # E731 Lambda Avoidance can be avoided
        # F841, F821 Does not work correctly. E402 does not work correctly because the imports can be seperated via comments.

# -   repo: https://github.com/PyCQA/pydocstyle
#     rev: 6.1.1
#     hooks:
#     -   id: pydocstyle
